# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pyupgrade
        name: Upgrade syntax for newer versions with pyupgrade
        entry: poetry run pyupgrade
        language: system
        pass_filenames: true
        types:
          - python
        args:
          - --py311-plus
          - --keep-runtime-typing

      - id: isort
        name: Sort import with isort
        entry: poetry run isort
        language: system
        pass_filenames: true
        types:
          - python

      - id: black
        name: Format with black
        entry: poetry run black
        language: system
        pass_filenames: true
        types:
          - python

      - id: flake8
        name: Check with flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
        types:
          - python
        args:
          - src

      - id: mypy
        name: Check types with mypy
        entry: poetry run mypy
        language: system
        types_or:
          - python
          - pyi
        require_serial: true
        pass_filenames: true
