version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data/file-manager
    environment:
      - PGDATA=/var/lib/postgresql/data/file-manager
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgresdata:
