version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
    - "8000:8000"

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data/file-manager
    environment:
      - PGDATA=/var/lib/postgresql/data/file-manager
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgresdata:
