"""file system node

Revision ID: b0b4659a218d
Revises:
Create Date: 2023-08-10 18:15:10.130218+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0b4659a218d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_system_node",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "is_folder",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Flag that shows that object is folder",
        ),
        sa.Column(
            "parent_folder_id",
            sa.Integer(),
            nullable=True,
            comment='When "parent_folder_id" IS NULL, then this object is root folder',
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_folder_id"],
            ["file_system_node.id"],
            name=op.f("file_system_node_parent_folder_id_fkey"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("file_system_node_pkey")),
        sa.UniqueConstraint("name", "is_folder", "parent_folder_id", name=op.f("file_system_node_name_key")),
    )
    op.create_index(op.f("file_system_node_id_idx"), "file_system_node", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("file_system_node_id_idx"), table_name="file_system_node")
    op.drop_table("file_system_node")
    # ### end Alembic commands ###
