"""file_system_node table

Revision ID: 853a4f7527af
Revises:
Create Date: 2023-02-08 12:23:15.919429+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "853a4f7527af"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_system_node",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "is_folder", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "parent_folder_id",
            sa.Integer(),
            nullable=True,
            comment='When "parent_folder_id" IS NULL, then this object is root folder',
        ),
        sa.ForeignKeyConstraint(
            ["parent_folder_id"],
            ["file_system_node.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "is_folder", "parent_folder_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_system_node")
    # ### end Alembic commands ###
